services:
  # ============================================
  # Core Infrastructure Services
  # ============================================

  # Redis - Caching Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - beckn_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  onix-bap:
    image: fidedocker/onix-adapter:latest
    container_name: onix-bap
    platform: linux/amd64
    networks:
      - beckn_network
    ports:
      - "8081:8081"
    environment:
      CONFIG_FILE: "/app/config/local-simple-bap.yaml"
      REDIS_ADDR: redis:6379
      RABBITMQ_ADDR: rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        mode: non-blocking
        tag: "beckn.bap.stdout"
    volumes:
      - ../config:/app/config
      - ../schemas:/app/schemas
    command: [ "./server", "--config=/app/config/local-simple-bap.yaml" ]

  onix-bpp:
    image: fidedocker/onix-adapter:latest
    container_name: onix-bpp
    platform: linux/amd64
    networks:
      - beckn_network
    ports:
      - "8082:8082"
    environment:
      CONFIG_FILE: "/app/config/local-simple-bpp.yaml"
      REDIS_ADDR: redis:6379
      RABBITMQ_ADDR: rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24225"
        fluentd-async: "true"
        mode: non-blocking
        tag: "beckn.bpp.stdout"
    volumes:
      - ../config:/app/config
      - ../schemas:/app/schemas
    command: [ "./server", "--config=/app/config/local-simple-bpp.yaml" ]

networks:
  beckn_network:
    name: beckn_network
    driver: bridge
