#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
DEVKIT_DIR="${REPO_ROOT}/testnet/retail-devkit"
INSTALL_DIR="${DEVKIT_DIR}/install"
COMPOSE_FILE="docker-compose-adapter.yml"
SECRETS_FILE="${DEVKIT_DIR}/config/onix-secrets.env"
VAULT_ENV_FILE="${DEVKIT_DIR}/config/onix-vault.env"
VAULT_CONTAINER="vault"
APPROLE_NAME="${APPROLE_NAME:-onix}"
POLICY_NAME="${POLICY_NAME:-onix-policy}"
VAULT_ADDR_IN_CONTAINER="http://127.0.0.1:8200"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd docker

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose plugin is required" >&2
  exit 1
fi

if [[ ! -f "${SECRETS_FILE}" ]]; then
  echo "Missing ${SECRETS_FILE}" >&2
  echo "Create it from ${DEVKIT_DIR}/config/onix-secrets.env.example first." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "${SECRETS_FILE}"
set +a

required_vars=(
  BAP_NETWORK_PARTICIPANT
  BAP_KEY_ID
  BAP_SIGNING_PUBLIC_KEY
  BAP_SIGNING_PRIVATE_KEY
  BAP_ENCR_PUBLIC_KEY
  BAP_ENCR_PRIVATE_KEY
  BPP_NETWORK_PARTICIPANT
  BPP_KEY_ID
  BPP_SIGNING_PUBLIC_KEY
  BPP_SIGNING_PRIVATE_KEY
  BPP_ENCR_PUBLIC_KEY
  BPP_ENCR_PRIVATE_KEY
)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Missing value for ${var} in ${SECRETS_FILE}" >&2
    exit 1
  fi
done

if [[ ! -f "${VAULT_ENV_FILE}" ]]; then
  cat > "${VAULT_ENV_FILE}" <<EOF
VAULT_ROLE_ID=bootstrap-placeholder
VAULT_SECRET_ID=bootstrap-placeholder
EOF
  chmod 600 "${VAULT_ENV_FILE}"
fi

cd "${INSTALL_DIR}"
docker compose -f "${COMPOSE_FILE}" up -d vault

echo "Waiting for Vault..."
for _ in $(seq 1 30); do
  if docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault status >/dev/null 2>&1"; then
    break
  fi
  sleep 1
done

if ! docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault status >/dev/null 2>&1"; then
  echo "Vault did not become ready" >&2
  exit 1
fi

docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault auth enable approle >/dev/null 2>&1 || true"
docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault secrets enable -path=secret kv-v2 >/dev/null 2>&1 || true"

docker exec -i "${VAULT_CONTAINER}" sh -lc "cat >/tmp/${POLICY_NAME}.hcl && export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault policy write '${POLICY_NAME}' /tmp/${POLICY_NAME}.hcl >/dev/null" <<'EOF'
path "secret/data/keys/*" {
  capabilities = ["read"]
}
EOF

docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; \
  vault kv put secret/keys/${BAP_NETWORK_PARTICIPANT} \
    uniqueKeyID='${BAP_KEY_ID}' \
    signingPublicKey='${BAP_SIGNING_PUBLIC_KEY}' \
    signingPrivateKey='${BAP_SIGNING_PRIVATE_KEY}' \
    encrPublicKey='${BAP_ENCR_PUBLIC_KEY}' \
    encrPrivateKey='${BAP_ENCR_PRIVATE_KEY}' >/dev/null"

docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; \
  vault kv put secret/keys/${BPP_NETWORK_PARTICIPANT} \
    uniqueKeyID='${BPP_KEY_ID}' \
    signingPublicKey='${BPP_SIGNING_PUBLIC_KEY}' \
    signingPrivateKey='${BPP_SIGNING_PRIVATE_KEY}' \
    encrPublicKey='${BPP_ENCR_PUBLIC_KEY}' \
    encrPrivateKey='${BPP_ENCR_PRIVATE_KEY}' >/dev/null"

docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; \
  vault write auth/approle/role/${APPROLE_NAME} token_policies='${POLICY_NAME}' token_ttl='1h' token_max_ttl='4h' >/dev/null"

ROLE_ID="$(docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault read -field=role_id auth/approle/role/${APPROLE_NAME}/role-id")"
SECRET_ID="$(docker exec "${VAULT_CONTAINER}" sh -lc "export VAULT_ADDR='${VAULT_ADDR_IN_CONTAINER}' VAULT_TOKEN=root; vault write -f -field=secret_id auth/approle/role/${APPROLE_NAME}/secret-id")"

cat > "${VAULT_ENV_FILE}" <<EOF
# Generated by scripts/setup-vault-dev.sh
VAULT_ROLE_ID=${ROLE_ID}
VAULT_SECRET_ID=${SECRET_ID}
EOF

chmod 600 "${VAULT_ENV_FILE}"

echo "Vault is configured for ONIX."
echo "Generated runtime file: ${VAULT_ENV_FILE}"
echo
echo "Verification commands:"
echo "  docker exec vault sh -lc \"export VAULT_ADDR=${VAULT_ADDR_IN_CONTAINER} VAULT_TOKEN=root; vault kv get secret/keys/${BAP_NETWORK_PARTICIPANT}\""
echo "  docker exec vault sh -lc \"export VAULT_ADDR=${VAULT_ADDR_IN_CONTAINER} VAULT_TOKEN=root; vault kv get secret/keys/${BPP_NETWORK_PARTICIPANT}\""
echo
echo "Next steps:"
echo "  cd ${INSTALL_DIR}"
echo "  docker compose -f ${COMPOSE_FILE} up -d"
echo "  docker compose -f ${COMPOSE_FILE} logs -f onix-bap onix-bpp vault"
