routingRules:
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://bapapp.remiges.tech/api/webhook"
    endpoints:
      - on_discover
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_cancel
      - on_support
